config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destory] do
    member do
      get :confirm
    end
  end
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users
    resources :employees

    root to: "users#index"
  end

  resources :posts do
    member do
      get :approve
    end
  end
  devise_for :users, skip: [:registrations]
  root "static#homepage"
end

app/views/share/_admin_dropdown.html.erb
<li>
  <%= link_to "Admin Dashboard", admin_root_path %>
</li>
<li class="divider"></li>

app/views/share/_alert.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], :title => "Overtime App Alert", sticky: false ) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], :title => "Overtime App Error", sticky: false ) %>
<% else %>
  <%= js add_gritter(flash[:notice], :title => "Overtime App Notification", sticky: false ) %>
<% end %>

app/views/share/_audit_log_tab.html.erb
<li class="<%= active?(audit_logs_path) %>">
  <%= link_to "Audit Log", audit_logs_path %>
</li>

app/views/share/_employee_nav_items.html.erb
<li class="<%= active?(posts_path) %>">
  <%= link_to "Entries", posts_path %>
</li>

<li class="<%= active?(new_post_path) %>">
  <%= link_to "Submit Hours", new_post_path, id: 'new_post_from_nav' %>
</li>

app/views/share/_nav.html.erb
<div class="logo">
  <h1>Time Tracker</h1>
</div>

<% if current_user.present? %>
  <nav class="custom-nav navbar navbar-default navbar-inverse navbar-static-top" role="navigation">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= active?(root_path) %>">
          <%= link_to "", root_path, class: 'glyphicon glyphicon-home' %>
        </li>
        <%= render "share/employee_nav_items" if employee? %>

        <%= render "share/audit_log_tab" if admin? %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.full_name if current_user.present? %><strong class="caret"></strong></a>
          <ul class="dropdown-menu">

            <%= render "share/admin_dropdown" if admin? %>

            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
<% end %>